export const tasks = [
  { id: 1, text: 'Visit the Boston Public Library' },
  { id: 2, text: 'Try cannoli at Mike\'s Pastry' },
  { id: 3, text: 'Walk the Freedom Trail' },
  { id: 4, text: 'Explore the Isabella Stewart Gardner Museum' },
  { id: 5, text: 'Have brunch at The Friendly Toast' },
  { id: 6, text: 'Visit the Boston Common' },
  { id: 7, text: 'Shop at Newbury Street' },
  { id: 8, text: 'Take a photo at Fenway Park' },
  { id: 9, text: 'Stroll through the North End' },
  { id: 10, text: 'Visit the Museum of Fine Arts' },
  { id: 11, text: 'Explore the Boston Public Market' },
  { id: 12, text: 'Take a Duck Tour' },
  { id: 13, text: 'Visit Harvard Square' },
  { id: 14, text: 'See the sea lions at the New England Aquarium' },
  { id: 15, text: 'Get a sandwich at Sam LaGrassa\'s' },
  { id: 16, text: 'Read a book at Trident Booksellers & Cafe' },
  { id: 17, text: 'Visit the MIT Museum' },
  { id: 18, text: 'Explore Beacon Hill' },
  { id: 19, text: 'Have lunch at Quincy Market' },
  { id: 20, text: 'Take a walk along the Charles River Esplanade' },
  { id: 21, text: 'Visit the Boston Tea Party Ships and Museum' },
  { id: 22, text: 'Try clam chowder at Legal Sea Foods' },
  { id: 23, text: 'Invite someone from the climbing gym out for drinks' },
  { id: 24, text: 'Visit Boston’s Museum of Science' },
  { id: 25, text: 'Check out the Harvard Museum of Natural History' },
  { id: 26, text: 'Have a meal at The Capital Grille' },
  { id: 27, text: 'Enjoy a craft beer at Samuel Adams Brewery' },
  { id: 28, text: 'Explore the Rose Kennedy Greenway' },
  { id: 29, text: 'Take a ferry to the Boston Harbor Islands' },
  { id: 30, text: 'Walk the grounds of the Boston University campus' },
  { id: 31, text: 'Start a conversation with a stranger at a coffee shop' },
  { id: 32, text: 'Join a local meetup group' },
  { id: 33, text: 'Attend a community event or festival' },
  { id: 34, text: 'Introduce yourself to a neighbor' },
  { id: 35, text: 'Ask a colleague to join you for lunch' },
  { id: 36, text: 'Explore the Arnold Arboretum' },
];
