export const tasks = [
  { id: 1, text: 'Visit the Boston Public Library' },
  { id: 2, text: 'Try cannoli at Mike\'s Pastry' },
  { id: 3, text: 'Walk the Freedom Trail' },
  { id: 4, text: 'Explore the Isabella Stewart Gardner Museum' },
  { id: 5, text: 'Have brunch at The Friendly Toast' },
  { id: 6, text: 'Visit the Boston Common' },
  { id: 7, text: 'Shop at Newbury Street' },
  { id: 8, text: 'Take a photo at Fenway Park' },
  { id: 9, text: 'Explore the Boston Bricks installation' },
  { id: 10, text: 'Browse the Cambridge Antique Market' },
  { id: 11, text: 'Explore the Boston Public Market' },
  { id: 12, text: 'Get coffee at George Howell’s Coffee (& see his wiki)' },
  { id: 13, text: 'Take a tour on Codzilla' },
  { id: 14, text: 'See the sea lions at the New England Aquarium' },
  { id: 15, text: 'Get a sandwich at Sam LaGrassa\'s' },
  { id: 16, text: 'Read a book at Trident Booksellers & Cafe' },
  { id: 17, text: 'Visit the MIT Museum' },
  { id: 18, text: 'Explore Beacon Hill' },
  { id: 19, text: 'Have lunch at Quincy Market' },
  { id: 20, text: 'Take a walk along the Charles River Esplanade' },
  { id: 21, text: 'Bike the Minuteman Trail' },
  { id: 22, text: 'Try clam chowder at Legal Sea Foods' },
  { id: 23, text: 'Invite someone from the climbing gym out for drinks' },
  { id: 24, text: 'Visit Boston’s Museum of Science' },
  { id: 25, text: 'Get treats from Clear Flour Bakery' },
  { id: 26, text: 'Visit the Museum of Bad Art' },
  { id: 27, text: 'Enjoy a craft beer at Samuel Adams Brewery' },
  { id: 28, text: 'Explore the Rose Kennedy Greenway' },
  { id: 29, text: 'Take a ferry to the Boston Harbor Islands' },
  { id: 30, text: 'Walk the grounds of the Boston University campus' },
];
